version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node  # Tek düðümlü modda çalýþacak
    ports:
      - "7257:9200"  # 7257 dýþ port, 9200 container iç portu
    volumes:
      - esdata:/usr/share/elasticsearch/data  # Verilerin kalýcý olmasý için volume
    networks:
      - elastic-network

networks:
  elastic-network:
    driver: bridge

volumes:
  esdata:
    driver: local
