namespace Entities.Enums
{
    public enum Operation_Type
    {
        Create,
        Update,
        Delete,
        Login,
        Logout,
        Access,
        FailedLogin,
        PasswordChange,
        PermissionChange,
        RoleAssignment,
        AccountLock,
        AccountUnlock,
        DataImport,
        DataExport,
        SystemConfigChange,
        Audit,
        NotificationSent,
        BatchProcessStart,
        BatchProcessEnd,
        BackupInitiated,
        FileUpload,
        FileDownload,
        SystemError,
        DataValidation,
        ApiAccess
    }
}
